//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ban
    {
        public Ban()
        {
            this.DatBans = new HashSet<DatBan>();
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int BanID { get; set; }
        public string TenBan { get; set; }
        public int SucChua { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<DatBan> DatBans { get; set; }
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
