//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatBan
    {
        public DatBan()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int DatBanID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public string ThongTinNguoiDat { get; set; }
        public int BanID { get; set; }
        public int SoNguoi { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime ThoiGianBatDau { get; set; }
        public System.DateTime ThoiGianKetThuc { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
