//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.CT_DonHang = new HashSet<CT_DonHang>();
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int DonHangID { get; set; }
        public int NhanVienID { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> BanID { get; set; }
        public Nullable<int> DatBanID { get; set; }
        public System.DateTime ThoiGianTao { get; set; }
        public decimal TongTien { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual ICollection<CT_DonHang> CT_DonHang { get; set; }
        public virtual DatBan DatBan { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
