//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiMon
    {
        public LoaiMon()
        {
            this.MonAns = new HashSet<MonAn>();
        }
    
        public int LoaiMonID { get; set; }
        public string TenLoai { get; set; }
    
        public virtual ICollection<MonAn> MonAns { get; set; }
    }
}
