//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNhaHangEntities1 : DbContext
    {
        public QLNhaHangEntities1()
            : base("name=QLNhaHangEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ban> Bans { get; set; }
        public DbSet<CT_DonHang> CT_DonHang { get; set; }
        public DbSet<DatBan> DatBans { get; set; }
        public DbSet<DonHang> DonHangs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LoaiMon> LoaiMons { get; set; }
        public DbSet<MonAn> MonAns { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
        public DbSet<TaiKhoan_VaiTro> TaiKhoan_VaiTro { get; set; }
        public DbSet<ThanhToan> ThanhToans { get; set; }
        public DbSet<VaiTro> VaiTroes { get; set; }
    }
}
