//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        public MonAn()
        {
            this.CT_DonHang = new HashSet<CT_DonHang>();
        }
    
        public int MonAnID { get; set; }
        public string TenMon { get; set; }
        public int LoaiMonID { get; set; }
        public string AnhMon { get; set; }
        public decimal DonGia { get; set; }
        public bool DangKinhDoanh { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<CT_DonHang> CT_DonHang { get; set; }
        public virtual LoaiMon LoaiMon { get; set; }
    }
}
