//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int NhanVienID { get; set; }
        public string HoTen { get; set; }
        public int TaiKhoanID { get; set; }
        public string ChucVu { get; set; }
        public decimal LuongCoBan { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
