//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan_VaiTro
    {
        public int ID { get; set; }
        public int TaiKhoanID { get; set; }
        public int VaiTroID { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual VaiTro VaiTro { get; set; }
    }
}
