//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int ThanhToanID { get; set; }
        public int DonHangID { get; set; }
        public System.DateTime ThoiGianTT { get; set; }
        public decimal SoTien { get; set; }
        public string PhuongThuc { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
