//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNha_Hang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaiTro
    {
        public VaiTro()
        {
            this.TaiKhoan_VaiTro = new HashSet<TaiKhoan_VaiTro>();
        }
    
        public int VaiTroID { get; set; }
        public string TenVaiTro { get; set; }
    
        public virtual ICollection<TaiKhoan_VaiTro> TaiKhoan_VaiTro { get; set; }
    }
}
